### PR TITLE
Delete this project, please

### PR DESCRIPTION
**Pull request by devclyde**

### CODE REVIEW

**Comment by NathaanScout** [comment]
Great Sage, Clyde. I totally approve of your opinion.

**Comment by juliobsz** [comment]
please.

**Comment by drethenrain** [comment]
maybe in the future

**Comment by c0dezinnn** [comment]
please

**Comment by drethenrain** [comment]
salve salve familia, se chegar a 100 mil likes e 10 mil inscritos a gente faz o que pediram!!! mete o dedo no like ai family

**Pull request closed without merging**
